# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Charlotte Swavola
email: cgswavola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Data can tell a story, but it takes hard work and creativity to tell it well.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cswavola.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: charlotte-swavola
twitter_username: CharDataSci
github_username:  cswavola

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Google Analytics
google_analytics: UA-179874529-1

collections:
  articles:
    output: true
    permalink: /:collection/:path

    defaults:
      -
        scope:
          path: ""
          type: category
        values:
          layout: home

  projects:
    output: true
    permalink: /:collection/:path

    defaults:
      -
        scope:
          path: ""
          type: category
        values:
          layout: home

collections_dir: my_collections

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
